#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""build_concept_dossier.py — concept-centric dossiers, and the claim index.

## Why the unit of analysis has to be the concept

Every per-unit review is structurally unable to find a cross-unit contradiction:
each reviewer sees one side of it and approves that side, correctly. This script
inverts the unit. For one concept it gathers EVERY prose passage across the whole
book that makes a claim about it, into one file, so a single auditor reads them
together and can notice that unit 8 and unit 18 disagree.

Source of truth is `final/`, never `manuscript.md` — the manuscript is derived.

## Three measured facts behind the design

  - The natural window is the PARAGRAPH, not a line and not ±N lines. Physical
    lines are merged back into paragraphs first (`bookkit.segment.paragraphs`) —
    a claim is a proposition and a proposition does not stop at column 80.
  - Code lives strictly inside fences, so a fence toggle beats a markdown parser.
  - Inline code spans are PROSE. Half the claims in a technical book live in a
    sentence that mentions a keyword in backticks. Only fenced blocks are cut.

## Modes

  --probe-report      per-concept coverage table (use this to tune probes)
  --concept <id>      emit one dossier
  --all               emit every dossier plus an index
  --emit-index        (re)generate bible/claim-index.yaml

Config
  bible/concept-probes.yaml         generated by bootstrap_probes.py
  bible/concept-probes-tuned.yaml   hand-written overrides, these win
  bible/audit-config.yaml           fix-run commits, persona names, thresholds
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("Missing PyYAML. Install with: pip install pyyaml")

sys.path.insert(0, str(Path(__file__).resolve().parent))

from bookkit.gitblame import blame_map, in_fix_run, is_repo  # noqa: E402
from bookkit.project import Project, add_common_args, load_project  # noqa: E402
from bookkit.selection import stratified_top  # noqa: E402
from bookkit.segment import (  # noqa: E402
    Record, fence_after, paragraphs, prev_prose, segment,
)
from bookkit.textmetrics import (  # noqa: E402
    RELATED_THRESHOLD, RELATED_TOP_K, content_terms, fingerprint, jaccard,
    stopwords_for,
)

ROLES = ["CANON", "repeats", "derives", "qualifies", "summary", "example", "crossref"]

# ---------------------------------------------------------------------------
# Claim scoring — it ORDERS, it does not filter.
# ---------------------------------------------------------------------------
# Filtering is tempting and wrong: the passage discarded for being "not very
# claim-like" is exactly the one that turns out to be canonical. Everything is
# emitted; the score only decides ordering and what gets trimmed from the home
# unit — which contributes ~80% of hits and is where the book contradicts itself
# LEAST.

RX_COPULA = re.compile(r"\b(is|are|means|refers to|is not|are not)\b", re.I)
RX_BEHAVIOR = re.compile(
    r"\b(returns?|evaluates?|expands?|resolves?|drops?|breaks?|fails?|refuses?|"
    r"reduces?|writes?|stores?|overwrites?|matches?|parses?|discards?|silently|"
    r"ignores?|collapses?|strips?|falls back|produces?|yields?|raises?|throws?)\b", re.I)
RX_MODAL = re.compile(
    r"\b(must|cannot|can't|never|always|only|no such|unconditionally|every|"
    r"does not|do not|will not|won't)\b", re.I)
RX_QUANT = re.compile(
    r"(\d+\s*(×|x\b|%|times|MB|GB|KB|ms|seconds|rows|bits|bytes)|"
    r"order of magnitude|orders of magnitude)", re.I)
RX_COND = re.compile(r"\b(if you|when you|unless|otherwise|as soon as|the instant)\b", re.I)
RX_CROSSREF = re.compile(
    r"(see Chapter|see §|in the next chapter|Chapter \d+ (covers|picks up|will)|"
    r"^Exercise \d|we'll come back|comes back in Chapter)", re.I)
RX_ANAPHORA = re.compile(r"^(This|That|It|These|Those|But|And|So|Which|Either|Both)\b")
# Rhetorical absolutes of a workshop register: "ship it", "do this, always".
# An imperative carrying an absolute is voice, not an engine claim.
RX_IMPERATIVE = re.compile(r"^(Do|Don't|Never|Always|Use|Keep|Treat|Put|Make|Avoid|Ship)\b")
RX_HEDGE = re.compile(
    r"\b(but|not a guarantee|unless|except|typically|roughly|usually|"
    r"in practice|tends to|often|generally|approximately|about)\b", re.I)

CLAIM_SCORE_THRESHOLD = 5


@dataclass
class AuditConfig:
    fix_run_commits: set[str] = field(default_factory=set)
    persona_names: list[str] = field(default_factory=list)
    home_cap: int = 12
    related_threshold: float = RELATED_THRESHOLD
    related_top_k: int = RELATED_TOP_K
    use_blame: bool = True

    @property
    def persona_re(self) -> re.Pattern | None:
        if not self.persona_names:
            return None
        return re.compile(r"\b(" + "|".join(
            re.escape(n) for n in self.persona_names) + r")\b")


def load_audit_config(project: Project) -> AuditConfig:
    raw = project.load_yaml("bible/audit-config.yaml")
    return AuditConfig(
        fix_run_commits={str(c) for c in (raw.get("fix_run_commits") or [])},
        persona_names=[str(n) for n in (raw.get("persona_names") or [])],
        home_cap=int(raw.get("home_cap", 12)),
        related_threshold=float(raw.get("related_threshold", RELATED_THRESHOLD)),
        related_top_k=int(raw.get("related_top_k", RELATED_TOP_K)),
        use_blame=bool(raw.get("use_blame", True)) and is_repo(project.root),
    )


def score_claim(text: str, term_rx: re.Pattern, cfg: AuditConfig) -> int:
    s = 0
    if RX_COPULA.search(text):
        s += 3
    if RX_BEHAVIOR.search(text):
        s += 3
    if RX_MODAL.search(text) and not RX_IMPERATIVE.match(text.strip()):
        s += 3
    if RX_QUANT.search(text):
        s += 2
    if RX_COND.search(text):
        s += 2
    if RX_CROSSREF.search(text):
        s -= 4
    # The running-example-persona penalty applies to PURE NARRATION only.
    #
    # MEASURED: without the copula/behavior guard this rule trimmed the canonical
    # passage of a cross-unit contradiction, because that passage opened with the
    # example character's name. A didactic book teaches its rules THROUGH the
    # running example, so penalizing a mention of the persona penalizes exactly
    # the claims that matter most. The regression gate caught it: without this
    # guard, the contradiction became undetectable, because only the wrong side
    # of it survived the trim.
    prx = cfg.persona_re
    if (prx and prx.search(text)
            and not RX_BEHAVIOR.search(text)
            and not RX_COPULA.search(text)):
        s -= 3
    if _bare_mention(text, term_rx):
        s -= 2
    return s


def _bare_mention(text: str, term_rx: re.Pattern) -> bool:
    """True when the term appears ONLY inside backticks — a mention, not a claim."""
    stripped = re.sub(r"`[^`]*`", " ", text)
    return bool(term_rx.search(text)) and not bool(term_rx.search(stripped))


def has_absolute(text: str) -> bool:
    return bool(RX_MODAL.search(text)) and not RX_IMPERATIVE.match(text.strip())


# ---------------------------------------------------------------------------


@dataclass
class Passage:
    unit: str
    path: str
    line: int
    kind: str
    heading_path: str
    text: str
    context: str = ""
    score: int = 0
    role: str = "body"
    blame_commit: str = ""
    blame_date: str = ""
    in_fix_run: bool = False
    code_ref: str = ""
    near_dup_of: list[str] = field(default_factory=list)
    absolute: bool = False
    hedged: bool = False
    numbers: list[str] = field(default_factory=list)

    @property
    def loc(self) -> str:
        return f"{self.path}:{self.line}"

    @property
    def fp(self) -> str:
        return fingerprint(self.text)


def build_passages(records_by_unit: dict[str, tuple[str, list[Record]]],
                   probe: dict, cfg: AuditConfig, project: Project) -> list[Passage]:
    # Case sensitivity matters. In many technical domains the keywords are also
    # ordinary English words (`SET`, `KEEP`, `JOIN`, `LOAD`). Without the flag a
    # probe for one of them returns triple-digit junk hits and the dossier is
    # unreadable.
    flags = 0 if probe.get("case_sensitive") else re.I
    inc = re.compile(probe["include"], flags)
    exc = re.compile(probe["exclude"], flags) if probe.get("exclude") else None
    out: list[Passage] = []

    for unit, (relpath, recs) in sorted(records_by_unit.items()):
        by_line = {r.line: r for r in recs}
        blame = blame_map(project.root, relpath, cfg.use_blame)

        for r in recs:
            if r.kind in ("code", "blank", "hr", "heading"):
                continue
            if not inc.search(r.text):
                continue
            if exc and exc.search(r.text):
                continue

            p = Passage(unit=unit, path=relpath, line=r.line, kind=r.kind,
                        heading_path=r.heading_path, text=r.text)
            p.score = score_claim(r.text, inc, cfg)
            p.absolute = has_absolute(r.text)
            p.hedged = bool(RX_HEDGE.search(r.text))
            p.numbers = [m.group(0) for m in RX_QUANT.finditer(r.text)]

            # Window: the whole paragraph. One exception — a leading anaphora
            # with no subject needs the sentence it refers back to, or the
            # auditor reads "It returns zero rows" with no idea what "it" is.
            if RX_ANAPHORA.match(r.text.strip()):
                prev = prev_prose(by_line, r.line)
                if prev:
                    p.context = prev.text

            # A bullet under `## Summary` can be the second side of a pair, never
            # the first: a summary restates, it does not establish.
            if r.kind == "bullet" and "Summary" in r.heading_path:
                p.role = "summary"
            elif re.search(r"\b(Exercise|Exercises|Practice)\b", r.heading_path):
                p.role = "exercise"

            # Code by reference, never by value. A technical book carries
            # thousands of lines of it and inlining turns dossiers into dumps.
            p.code_ref = fence_after(by_line, r.line, relpath)

            bm = blame.get(r.line)
            if bm:
                p.blame_commit, p.blame_date = bm
                p.in_fix_run = in_fix_run(p.blame_commit, cfg.fix_run_commits)

            out.append(p)

    return out


def mark_related(passages: list[Passage], cfg: AuditConfig,
                 stopwords: set[str]) -> list[tuple[float, Passage, Passage]]:
    """Similarity graph over passages. Returns PAIRS, not connected components.

    With a threshold this low the transitive closure collapses a whole unit into
    one 30-passage "cluster", which tells the auditor nothing. A pair does:
    "these two make the same claim, and one was touched in a fix run and the
    other was not" is directly actionable.
    """
    terms = [content_terms(p.text, stopwords) for p in passages]
    n = len(passages)
    neighbours: dict[int, list[tuple[float, int]]] = {i: [] for i in range(n)}

    for i in range(n):
        for j in range(i + 1, n):
            s = jaccard(terms[i], terms[j])
            if s >= cfg.related_threshold:
                neighbours[i].append((s, j))
                neighbours[j].append((s, i))

    pairs: list[tuple[float, Passage, Passage]] = []
    for i in range(n):
        top = sorted(neighbours[i], reverse=True)[:cfg.related_top_k]
        passages[i].near_dup_of = [f"{passages[j].loc} ({s:.2f})" for s, j in top]
        for s, j in neighbours[i]:
            if i < j:
                pairs.append((s, passages[i], passages[j]))

    pairs.sort(key=lambda t: -t[0])
    return pairs


# ---------------------------------------------------------------------------
# Dossier emission
# ---------------------------------------------------------------------------


def emit_dossier(cid: str, probe: dict, node: dict, passages: list[Passage],
                 pairs: list[tuple[float, Passage, Passage]], cfg: AuditConfig) -> str:
    home = probe.get("home") or node.get("introduced_in") or ""

    kg_span = [c for c in sorted(
        ({node.get("introduced_in", "")}
         | set(node.get("reinforced_in") or [])
         | set(node.get("hinted_in") or [])) - {""}) if c]
    text_span = sorted({p.unit for p in passages})

    # Home-unit cap. Every other unit is uncapped.
    #
    # INVARIANT, learned from the regression gate: a home-unit passage that is
    # cross-linked to a passage in ANOTHER unit is NEVER trimmed, whatever its
    # score. It is precisely the passage that can contradict — or vindicate —
    # the other unit, and therefore the whole reason the dossier exists.
    # Trimming it by score leaves the auditor looking at one side only.
    cross_linked = {
        p.line for p in passages
        if p.unit == home and any(
            not ref.startswith(f"{p.path}:") for ref in p.near_dup_of)
    }
    home_ps = sorted([p for p in passages if p.unit == home],
                     key=lambda p: (-p.score, p.line))
    kept_home = {p.line for p in home_ps[:cfg.home_cap]} | cross_linked
    kept = [p for p in passages if p.unit != home or p.line in kept_home]
    dropped = len(passages) - len(kept)

    # D2 = a related pair where ONE side was touched in a fix run and the other
    # was not. That is the mechanical signature of "the fix landed in 1 of N
    # sites" — detected without spending a token on an LLM.
    d2 = [f"{a.loc} [{a.blame_commit or '—'}{' FIX' if a.in_fix_run else ''}] "
          f"<-> {b.loc} [{b.blame_commit or '—'}{' FIX' if b.in_fix_run else ''}]"
          for _s, a, b in pairs if a.in_fix_run != b.in_fix_run][:15]

    L: list[str] = ["---",
                    f"concept: {cid}",
                    f"name: {node.get('name', probe.get('name', cid))!r}",
                    f"kind: {node.get('kind', 'unknown')}",
                    f"home: {home}",
                    f"kg_span: [{', '.join(kg_span)}]",
                    f"text_span: [{', '.join(text_span)}]"]
    only_text = [c for c in text_span if c not in kg_span]
    only_kg = [c for c in kg_span if c not in text_span]
    L.append(f"kg_drift: {{text_only: [{', '.join(only_text)}], "
             f"kg_only: [{', '.join(only_kg)}]}}")
    L.append(f"passages_total: {len(passages)}  # {dropped} trimmed from the home unit")
    if d2:
        L.append("d2_candidates:   # related pairs with DIVERGENT blame -> possible incomplete fix")
        L += [f"  - {s}" for s in d2]
    L += ["---", "", "## Passages", ""]

    for p in sorted(kept, key=lambda p: (p.unit, p.line)):
        flags = []
        if p.score >= CLAIM_SCORE_THRESHOLD:
            flags.append("claim")
        if p.role != "body":
            flags.append(p.role)
        if p.absolute:
            flags.append("ABSOLUTE")
        if p.hedged:
            flags.append("hedged")
        blame = f"{p.blame_commit} {p.blame_date}".strip() if p.blame_commit else "—"
        if p.in_fix_run:
            blame += " FIX-RUN"
        L.append(f"### {p.loc}  [score {p.score}] [{' '.join(flags) or '—'}] "
                 f"[blame {blame}] [fp {p.fp}]")
        L += [f"> {p.heading_path}", ""]
        if p.context:
            L += [f"*(preceding context)* {p.context}", ""]
        L += [p.text, ""]
        if p.near_dup_of:
            L.append(f"`related_to:` {', '.join(p.near_dup_of)}")
        if p.code_ref:
            L.append(f"`code_ref:` {p.code_ref}")
        if p.near_dup_of or p.code_ref:
            L.append("")

    # Homonym watch — SEPARATE from Passages on purpose. Merged in, the auditor
    # reads two different referents as one claim and emits a false contradiction.
    # That is the predicted false positive number one.
    if probe.get("homonym_guard"):
        L += ["## Homonym watch", "", f"Guard: `{probe['homonym_guard']}`", ""]
        hg = re.compile(probe["homonym_guard"], re.I)
        hits = [p for p in passages if hg.search(p.text)]
        L += ([f"- {p.loc} — {p.text[:200]}"
               for p in sorted(hits, key=lambda p: (p.unit, p.line))]
              or ["_No guard hits._"])
        L.append("")

    nums = [p for p in passages if p.numbers]
    if nums:
        L += ["## Numbers table", "",
              "| Site | Quantity | Declared baseline (for the auditor to fill) |",
              "|---|---|---|"]
        L += [f"| {p.loc} | {', '.join(p.numbers)} | |"
              for p in sorted(nums, key=lambda p: (p.unit, p.line))]
        L.append("")

    if node:
        L += ["## Knowledge-graph record", "", "```yaml",
              yaml.safe_dump(node, allow_unicode=True, sort_keys=False).strip(),
              "```", ""]

    return "\n".join(L)


# ---------------------------------------------------------------------------
# Claim index emission
# ---------------------------------------------------------------------------


def emit_index(project: Project, records_by_unit, kg, probes,
               cfg: AuditConfig, stopwords: set[str], out_path: Path) -> int:
    """Generate bible/claim-index.yaml.

    It stores a FINGERPRINT per passage, not a line number. If a passage MOVES
    the validator re-finds it and repairs the line; if a passage was EDITED the
    fingerprint disappears and the validator flags every sibling as suspect.
    That is the incomplete-fix detector, and the reason this does not go stale
    the way a hand-ticked checklist does.

    Roles are assigned by the audit, not by this script: everything ships as
    `repeats` except the strongest claim in the home unit, which starts as a
    provisional CANON. A human decision, once made, is never overwritten.
    """
    concepts: dict[str, dict] = {}

    prior: dict[str, dict[str, str]] = {}
    prior_meta: dict[str, dict] = {}
    if out_path.exists():
        old = yaml.safe_load(out_path.read_text(encoding="utf-8")) or {}
        for cid, entry in (old.get("concepts") or {}).items():
            prior[cid] = {s["fingerprint"]: s.get("role", "repeats")
                          for s in entry.get("sites", []) if s.get("fingerprint")}
            prior_meta[cid] = {
                "verified_against": entry.get("verified_against"),
                "do_not_touch": entry.get("do_not_touch", False),
                "note": entry.get("note"),
            }

    for cid, probe in probes.items():
        ps = build_passages(records_by_unit, probe, cfg, project)
        mark_related(ps, cfg, stopwords)
        claims = [p for p in ps if p.score >= CLAIM_SCORE_THRESHOLD]
        if not claims:
            continue

        node = kg.get(cid, {})
        home = probe.get("home") or node.get("introduced_in") or ""
        home_claims = [p for p in claims if p.unit == home]
        best = (max(home_claims, key=lambda p: p.score) if home_claims
                else max(claims, key=lambda p: p.score))

        # `related` is what makes PROPAGATE usable. Without it, editing one
        # passage sends you to review all 65 sites of the concept — and a warning
        # that asks for that gets ignored, which is exactly how the checklist
        # this replaces went stale. With it, you review the 3 or 4 that carry the
        # same sub-claim.
        terms = {p.loc: content_terms(p.text, stopwords) for p in claims}

        sites = []
        for p in sorted(claims, key=lambda p: (p.unit, p.line)):
            role = prior.get(cid, {}).get(p.fp)
            if role is None:
                role = ("CANON" if p is best else
                        "summary" if p.role == "summary" else
                        "example" if p.role == "exercise" else "repeats")
            rel = sorted(((jaccard(terms[p.loc], terms[q.loc]), q.loc)
                          for q in claims if q.loc != p.loc), reverse=True)
            sites.append({
                "location": p.loc,
                "role": role,
                "fingerprint": p.fp,
                "claim": p.text[:110].rstrip() + ("…" if len(p.text) > 110 else ""),
                "blame": f"{p.blame_commit} {p.blame_date}".strip() or "—",
                "related": [loc for s, loc in rel
                            if s >= cfg.related_threshold][:cfg.related_top_k],
            })

        meta = prior_meta.get(cid, {})
        concepts[cid] = {
            "name": node.get("name", probe.get("name", cid)),
            "home": home,
            # Positive verdicts are first-class. `verified_against` closes a
            # concept against a source; `do_not_touch` is the auto-refutation
            # anchor that stops a later pass from "fixing" correct text.
            "verified_against": meta.get("verified_against"),
            "do_not_touch": meta.get("do_not_touch", False),
            "note": meta.get("note"),
            "sites": sites,
        }

    doc = {
        "# generated by": "scripts/build_concept_dossier.py --emit-index — do not hand-edit sites",
        "# hand-editable": "role, verified_against, do_not_touch, note — these are preserved",
        "# roles": " | ".join(ROLES),
        "# validate": "python scripts/validate_claim_index.py",
        "schema_version": "1.0",
        "concepts": concepts,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        yaml.safe_dump(doc, allow_unicode=True, sort_keys=False, width=200),
        encoding="utf-8")

    n_sites = sum(len(c["sites"]) for c in concepts.values())
    n_prior = sum(len(v) for v in prior.values())
    print(f"[claim-index] {len(concepts)} concept(s), {n_sites} site(s) "
          f"({n_prior} prior role decision(s) preserved) → {out_path}")
    return 0


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def load_kg(project: Project) -> dict[str, dict]:
    """Knowledge graph by id. Empty when the project has none (standalone)."""
    d = project.load_yaml("bible/knowledge-graph.yaml")
    return {c["id"]: c for c in (d.get("concepts") or []) if c.get("id")}


def load_probes(project: Project) -> dict[str, dict]:
    """Generated base plus hand-written overrides.

    Tuned probes WIN and may introduce ids with no knowledge-graph node: the
    concept that actually contradicts itself is usually finer-grained than a
    graph node. A defect can live in one sense of a term while the node covering
    it looks perfectly consistent.
    """
    base = project.load_yaml("bible/concept-probes.yaml")
    if not base:
        sys.exit("No bible/concept-probes.yaml. Run scripts/bootstrap_probes.py first.")
    probes = {p["id"]: p for p in base.get("probes", []) if p.get("id")}

    tuned = project.load_yaml("bible/concept-probes-tuned.yaml")
    for p in tuned.get("probes", []) or []:
        if p.get("id"):
            probes[p["id"]] = p
    return probes


def load_records(project: Project) -> dict[str, tuple[str, list[Record]]]:
    out: dict[str, tuple[str, list[Record]]] = {}
    for path in project.unit_paths:
        rel = project.rel(path)
        recs = segment(path, rel_to=project.root)
        for r in recs:
            r.path = rel
        # Claims are reasoned over LOGICAL paragraphs, not physical lines.
        # See bookkit.segment.paragraphs for why this is not cosmetic.
        out[path.stem] = (rel, paragraphs(recs))
    return out


# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Concept-centric dossiers and the claim index.")
    add_common_args(ap)
    ap.add_argument("--probe-report", action="store_true",
                    help="Coverage table per concept; use it to tune probes.")
    ap.add_argument("--concept", help="Emit one dossier by concept id.")
    ap.add_argument("--all", action="store_true", help="Emit every dossier plus an index.")
    ap.add_argument("--emit-index", action="store_true",
                    help="(Re)generate bible/claim-index.yaml.")
    ap.add_argument("--out", default=None,
                    help="Dossier output dir (default: reviews/concept-dossiers/).")
    ap.add_argument("--index-path", default="bible/claim-index.yaml")
    ap.add_argument("--no-blame", action="store_true",
                    help="Skip git blame (disables the D2 incomplete-fix detector).")
    ap.add_argument("--only", action="append", default=[],
                    help="Restrict to these concept ids, repeatable.")
    ap.add_argument("--min-units", type=int, default=1,
                    help="Skip concepts spanning fewer units than this. The gate uses 2: "
                         "a concept confined to one unit cannot carry a cross-unit "
                         "contradiction, and the Critic already read that unit.")
    ap.add_argument("--top", type=int, default=0,
                    help="Emit only the top N concepts by cross-unit reach (0 = all). "
                         "One agent run per concept per lens, so this is the cost dial. "
                         "Whatever is cut is reported.")
    # The next two mirror bible/audit-config.yaml. They exist so a retrofit run
    # over a finished book can enable the D2 detector and the persona guard
    # without writing config files into someone else's project.
    ap.add_argument("--fix-run-commit", action="append", default=[], metavar="SHA",
                    help="Short sha of a fix-pass commit, repeatable. Enables the D2 "
                         "detector: a related pair with one side touched in a fix run "
                         "and the other not is an incomplete fix.")
    ap.add_argument("--persona", action="append", default=[], metavar="NAME",
                    help="Running-example character name, repeatable. Used only to "
                         "down-rank pure narration; guarded so it never trims a claim.")
    args = ap.parse_args(argv)

    project = load_project(args.root, args.units)
    cfg = load_audit_config(project)
    if args.no_blame:
        cfg.use_blame = False
    cfg.fix_run_commits |= {s.strip() for s in args.fix_run_commit if s.strip()}
    cfg.persona_names += [n for n in args.persona if n.strip()]
    stopwords = stopwords_for(project.language_variant)

    probes = load_probes(project)
    if args.only:
        probes = {k: v for k, v in probes.items() if k in set(args.only)}
        if not probes:
            sys.exit(f"None of {args.only} is a known probe id.")
    kg = load_kg(project)
    records = load_records(project)

    if args.emit_index:
        return emit_index(project, records, kg, probes, cfg, stopwords,
                          project.root / args.index_path)

    if args.probe_report:
        print(f"{'concept':28} {'prose':>6} {'units':>6} {'claims':>7}  distribution")
        print("-" * 96)
        for cid, probe in sorted(probes.items()):
            ps = build_passages(records, probe, cfg, project)
            claims = [p for p in ps if p.score >= CLAIM_SCORE_THRESHOLD]
            units = sorted({p.unit for p in ps})
            dist = " ".join(f"{u}:{sum(1 for p in ps if p.unit == u)}" for u in units)
            print(f"{cid:28} {len(ps):>6} {len(units):>6} {len(claims):>7}  {dist[:60]}")
        return 0

    out_dir = Path(args.out) if args.out else project.reviews / "concept-dossiers"
    targets = [args.concept] if args.concept else (sorted(probes) if args.all else [])
    if not targets:
        ap.error("Pick a mode: --probe-report, --concept ID, --all, or --emit-index.")

    out_dir.mkdir(parents=True, exist_ok=True)
    rows: list[tuple[str, int, int, int]] = []

    # Build first, rank second, emit third. Ranking needs the unit span, and the
    # span is only known after the passages are gathered.
    built: list[tuple[str, dict, list[Passage], list, int, int]] = []
    skipped_span = 0
    for cid in targets:
        probe = probes.get(cid)
        if not probe:
            print(f"[dossier] unknown concept id: {cid}")
            continue
        ps = build_passages(records, probe, cfg, project)
        if not ps:
            print(f"[dossier] {cid}: no passages matched — tune the probe.")
            continue
        span = len({p.unit for p in ps})
        if span < args.min_units:
            skipped_span += 1
            continue
        pairs = mark_related(ps, cfg, stopwords)
        d2 = sum(1 for _s, a, b in pairs if a.in_fix_run != b.in_fix_run)
        built.append((cid, probe, ps, pairs, span, d2))

    # Two failure modes, two quotas.
    #
    # A pre-flagged incomplete fix (D2) is the highest-yield thing an auditor can
    # open, so it would be tempting to rank purely on it. Do not: ranking two
    # modes on one scale lets the more numerous one starve the other completely,
    # and on a real book that emitted 40 of one mode and zero of the other.
    # `bookkit.selection` exists for exactly this.
    selection = stratified_top(
        built,
        stratum_of=lambda t: "incomplete-fix" if t[5] else "cross-unit",
        rank_within=lambda t: (-t[5], -t[4], t[0]),
        quota=args.top,
        weights={"incomplete-fix": 1.0, "cross-unit": 1.0},
    )
    emitted = selection.emitted
    cut = selection.dropped_total

    for cid, probe, ps, pairs, span, d2 in emitted:
        text = emit_dossier(cid, probe, kg.get(cid, {}), ps, pairs, cfg)
        (out_dir / f"{cid}.md").write_text(text, encoding="utf-8")
        rows.append((cid, len(ps), len(pairs), d2))
        if not args.all:
            print(f"[dossier] {cid}: {len(ps)} passages, {len(pairs)} related pairs, "
                  f"{d2} D2 candidate(s) → {out_dir / (cid + '.md')}")

    if skipped_span:
        print(f"[dossier] {skipped_span} concept(s) skipped: they span fewer than "
              f"{args.min_units} unit(s).")
    for line in selection.report_lines("concept"):
        print(f"[dossier] {line}")
    if cut:
        print(f"[dossier] {cut} concept(s) NOT emitted because of --top {args.top}. "
              f"MG-1 coverage is partial this round.")

    if args.all and rows:
        idx = ["# Concept dossier index", "",
               "| Concept | Passages | Related pairs | D2 candidates |",
               "|---|---:|---:|---:|"]
        idx += [f"| [{c}]({c}.md) | {n} | {pr} | {d} |" for c, n, pr, d in
                sorted(rows, key=lambda r: -r[3])]
        idx += ["", "D2 = a related pair whose two sides have divergent git blame: one was "
                    "touched in a declared fix run and the other was not. That is the "
                    "mechanical signature of a fix that landed in 1 of N sites. "
                    "**Start there.**"]
        if cut:
            idx += ["", f"> **{cut} concept(s) below the cut were not emitted.** MG-1 "
                        f"coverage this round is partial, and the gate report must say so."]
        (out_dir / "_index.md").write_text("\n".join(idx) + "\n", encoding="utf-8")
        print(f"[dossier] {len(rows)} dossier(s), index → {out_dir / '_index.md'}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
