#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""sync_manuscript.py — rebuild manuscript.md from final/ deterministically.

`final/unit-NN.md` is the source of truth; `manuscript.md` is derived. That
direction has to be mechanical, or the two drift and every later check has to
guess which one to trust. The Phase 4 instruction used to be "concatenate",
which is where the drift came from — two people concatenate differently.

`--check` makes the derivation verifiable: it rebuilds in memory and reports
whether the file on disk matches, without writing. That is what the build
preflight runs.

Usage
  python scripts/sync_manuscript.py                  # write manuscript.md
  python scripts/sync_manuscript.py --check          # verify, never write
  python scripts/sync_manuscript.py --out build/manuscript.md
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from bookkit.project import add_common_args, load_project  # noqa: E402

BANNER = ("<!-- GENERATED by scripts/sync_manuscript.py from final/. "
          "Edit final/, never this file. -->")


def build(paths: list[Path], *, banner: bool = True,
          separator: str = "\n\n") -> str:
    """Concatenate units into one document.

    Each unit contributes its text with trailing whitespace normalized to a
    single newline, joined by exactly one blank line. Normalizing here rather
    than trusting the files is what makes the output stable across editors that
    disagree about final newlines.
    """
    chunks: list[str] = []
    if banner:
        chunks.append(BANNER)
    for p in paths:
        chunks.append(p.read_text(encoding="utf-8").rstrip("\n"))
    return separator.join(chunks) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Rebuild manuscript.md from final/ units, deterministically.")
    add_common_args(ap)
    ap.add_argument("--out", default=None,
                    help="Output path (default: <root>/manuscript.md).")
    ap.add_argument("--check", action="store_true",
                    help="Verify the existing file matches; never write. Exit 1 on drift.")
    ap.add_argument("--no-banner", action="store_true",
                    help="Omit the generated-file banner.")
    ap.add_argument("--diff", action="store_true",
                    help="With --check, print a unified diff of the drift.")
    args = ap.parse_args(argv)

    project = load_project(args.root, args.units)
    out_path = Path(args.out) if args.out else project.manuscript
    text = build(project.unit_paths, banner=not args.no_banner)

    names = ", ".join(p.stem for p in project.unit_paths[:3])
    more = f" … +{len(project.unit_paths) - 3}" if len(project.unit_paths) > 3 else ""

    if args.check:
        if not out_path.exists():
            print(f"[sync_manuscript] DRIFT — {out_path} does not exist.")
            return 1
        current = out_path.read_text(encoding="utf-8")
        if current == text:
            print(f"[sync_manuscript] OK — {out_path.name} matches "
                  f"{len(project.unit_paths)} unit(s) ({names}{more}).")
            return 0
        print(f"[sync_manuscript] DRIFT — {out_path.name} does not match final/. "
              f"Rebuild it, or find out who edited the derived file.")
        if args.diff:
            for line in difflib.unified_diff(
                    current.splitlines(), text.splitlines(),
                    fromfile=f"{out_path.name} (on disk)",
                    tofile="rebuilt from final/", lineterm="", n=2):
                print(line)
        return 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    words = len(text.split())
    print(f"[sync_manuscript] wrote {out_path} — {len(project.unit_paths)} unit(s), "
          f"{words:,} words ({names}{more}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
